# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy Demo site to Pages

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  deploy-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Site
        run: pnpm build:h5

      - name: Deploy for Gitee 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: dist/build/h5
          # enable single-commit to reduce the repo size
          single-commit: true
          clean: true

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1.2.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:Moonofweisheng/wot-starter-retail.git
          destination-repo: git@gitee.com:Moonofweisheng/wot-starter-retail.git
  
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: Moonofweisheng
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: Moonofweisheng/wot-starter-retail
          branch: gh-pages
